using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace AdminManager.Web.Models
{
    public class ReceiptPdfDocument : IDocument
    {
        private readonly ReceiptPdfModel Model;

        public ReceiptPdfDocument(ReceiptPdfModel model)
        {
            Model = model;
        }

        public DocumentMetadata GetMetadata() =>
            new DocumentMetadata { Title = $"Receipt {Model.SaleId}" };

        public void Compose(IDocumentContainer container)
        {
            container.Page(page =>
            {
                page.Margin(30);
                page.Size(PageSizes.A4);

                page.Header().Text($"Receipt #{Model.SaleId}")
                    .FontSize(22).SemiBold().FontColor("#333");

                page.Content().Column(col =>
                {
                    col.Item().Text($"Date: {Model.Date:yyyy-MM-dd}");
                    col.Item().Text($"Client: {Model.ClientEmail}");
                    if (!string.IsNullOrWhiteSpace(Model.ClientPhone))
                        col.Item().Text($"Phone: {Model.ClientPhone}");

                    col.Item().PaddingVertical(10)
                        .LineHorizontal(1);

                    // Tabla de productos
                    col.Item().Table(table =>
                    {
                        table.ColumnsDefinition(c =>
                        {
                            c.RelativeColumn(3);  // name
                            c.RelativeColumn(1);  // qty
                            c.RelativeColumn(1);  // unit price
                            c.RelativeColumn(1);  // total
                        });

                        table.Header(header =>
                        {
                            header.Cell().Element(StyleHeader).Text("Product");
                            header.Cell().Element(StyleHeader).Text("Qty");
                            header.Cell().Element(StyleHeader).Text("Unit");
                            header.Cell().Element(StyleHeader).Text("Total");
                        });

                        static IContainer StyleHeader(IContainer c) =>
                            c.Background("#EEE").Padding(5).BorderBottom(1);

                        foreach (var p in Model.Products)
                        {
                            table.Cell().Padding(5).Text(p.Name);
                            table.Cell().Padding(5).Text(p.Quantity);
                            table.Cell().Padding(5).Text($"{p.UnitPrice:C}");
                            table.Cell().Padding(5).Text($"{p.Total:C}");
                        }
                    });

                    col.Item().PaddingTop(15).AlignRight().Column(totals =>
                    {
                        totals.Item().Text($"Subtotal: {Model.SubTotal:C}");
                        totals.Item().Text($"VAT (19%): {Model.VAT:C}");
                        totals.Item().Text($"Total: {Model.Total:C}")
                            .SemiBold();
                    });
                });

                page.Footer().AlignCenter()
                    .Text("Generated by AdminManager");
            });
        }
    }

}
