server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        # Si el archivo existe, sírvelo ($uri).
        # Si no existe, intenta servir $uri/ (un directorio).
        # Si nada de lo anterior funciona, sirve index.html y deja que Vue se encargue.
        try_files $uri $uri/ /index.html;
    }

    # Deshabilitar logs de Nginx para archivos estáticos (opcional, para limpieza)
    location ~* \.(?:css|js|gif|jpe?g|png|ico)$ {
        expires 1y;
        log_not_found off;
    }
}